version: "3"
services:
    grafana:
        image: grafana/grafana-arm32v7-linux
        container_name: grafana
        restart: always
        ports:
            - 3000:3000
        networks:
            - monitoring
        volumes:
            - grafana-volume:/var/lib/grafana  
    influxdb:
        image: influxdb
        container_name: influxdb
        restart: always
        environment:
            - INFLUXDB_DB=telegraf 
            - INFLUXDB_ADMIN_ENABLED=true
            - INFLUXDB_ADMIN_USER=admin
            - INFLUXDB_ADMIN_PASSWORD=supersecretpassword
            - INFLUXDB_USER=telegraf 
            - INFLUXDB_USER_PASSWORD=secretpassword 
        ports:
            - 8083:8083
            - 8086:8086
        networks:
            - monitoring
        volumes:
            - influxdb-volume:/var/lib/influxdb
            - ./.docker-compose/influxdb/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    speedtest:
        image: atribe/speedtest-for-influxdb-and-grafana:latest
        container_name: speedtest
        network_mode: host
        volumes:
        - ./speedtest/config.ini:/src/config.ini
        depends_on:
        - influxdb
        restart: always
    telegraf:
        image: telegraf:latest
        container_name: telegraf
        links:
            - influxdb
        volumes:
            - ./.docker-compose/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
networks:
    monitoring:
volumes:
    grafana-volume:
        external: true
    influxdb-volume:
        external: true